# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-03 10:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Stud_information',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('COMPANY', models.CharField(max_length=100)),
                ('TITLE', models.CharField(max_length=100)),
                ('ELIGIBILITY', models.CharField(max_length=100)),
                ('ADDRESS', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PHONENUMBER', models.IntegerField()),
            ],
        ),
    ]
