# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-04 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Stud_information',
            new_name='Hyd_Job',
        ),
    ]
