# -*- coding: utf-8 -*-
# Generated by Django 1.11.26 on 2020-02-04 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('testapp', '0002_auto_20200204_1440'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bangalora_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('COMPANY', models.CharField(max_length=100)),
                ('TITLE', models.CharField(max_length=100)),
                ('ELIGIBILITY', models.CharField(max_length=100)),
                ('ADDRESS', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PHONENUMBER', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Mumbai_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('COMPANY', models.CharField(max_length=100)),
                ('TITLE', models.CharField(max_length=100)),
                ('ELIGIBILITY', models.CharField(max_length=100)),
                ('ADDRESS', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PHONENUMBER', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Pune_Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DATE', models.DateField()),
                ('COMPANY', models.CharField(max_length=100)),
                ('TITLE', models.CharField(max_length=100)),
                ('ELIGIBILITY', models.CharField(max_length=100)),
                ('ADDRESS', models.CharField(max_length=100)),
                ('EMAIL', models.EmailField(max_length=254)),
                ('PHONENUMBER', models.IntegerField()),
            ],
        ),
    ]
